### ISSUE TITLE
Publish a poll

### ISSUE THREAD

**Issue by SophieTiger** [SophieTiger/loverunning#3]
n order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

### Acceptance criteria

- Acceptance criteria 1: The poll should disappear at 11.59pm on target date
- Acceptance criteria 2: The poll should be active for 2 days from initial date
- Acceptance criteria 3: The poll should be visible on the home page.

### Tasks

- [x] Create the module and design with HTML and CSS
- [ ] Create Javascript function to validate the 2 day rule
- [ ] Test the functionality
